### ISSUE TITLE
Změnu faktorů států mít jako pop-up formulář s nastavitelnými hodnotami a jedním odesláním všeho najednou (P3)

### ISSUE THREAD

**Issue by lomikel** [Dimitros617/Climate_rules#20]
v přehledu "svět" v admin módu při kliknutí na název státu otevřít formulář, kde se zobrazí možnost zadat změnu jakékoli hodnoty faktorů. Bylo by asi fajn, kdyby kliknutím na šipky jako je to nyní v pohledu, šlo navyšovat/snižovat, přičemž musí jít zadat (naklikat) i minusové hodnoty. 
Formulářík bude mít také potvrzovací zaklikávátko "Potvrzuji zadané hodnoty pro aktualizace dat států ...."
Po kliknutí na "uložit" se pak všechny zadané hodnoty přičtou k těm dosavadním. 
Možná by bylo skvělé, kdyby se např. v levé části formuláře ukázaly původní hodnoty a pod tím pak, jak budou vypadat po připočtení oněch změn.

**Comment by Dimitros617** [comment]
2 možnosti z karty "svět" po kliknutí na název státu, nebo z karty stát přímo kliknutím na jinou hodnotu.
