### ISSUE TITLE
Domluvit a případně upravit viditelnost lobby (P3)

### ISSUE THREAD

**Issue by lomikel** [Dimitros617/Climate_rules#27]
Nyní je to tak, že po přihlášení uživatel vidí všechna aktivní (viditelná) lobby - i ta, kam nemá přístup, což ale na první pohled nepozná. Je vhodné prodiskutovat vhodnost zobrazení (Dominik, Pavel, Lomi, možná Niky, Anička, Eva).
Možnosti jsou asi 3:
- uvidí všechna aktivní lobby jako nyní; pokud tam není evidován, dá mu to hlášku (viz úprava chybové hlášky),  
- uvidí všechna aktivní lobby, ale ty, kam nemá přístup, budou šedivé (jako je to nyní u skrytých lobby), 
- uvidí pouze ty, kam je přiřazen jako uživatel.

**Comment by Dimitros617** [comment]
Zobrazil bych všechna lobby jen ty do kterých nemá uživatel přístup bych zobrazil šedivě a se zámečkem.
