### ISSUE TITLE
Přihlášení uživatele se daří až napodruhé - prosím ověřit důvod zrušení přihlášení (CHYBA) 

### ISSUE THREAD

**Issue by lomikel** [Dimitros617/Climate_rules#38]
Když se přihlašuji pod nějakým uživatelem, první přihlášení neproběhne. Zadám jméno a heslo, poté potvrdím přihlášení, problikne obrazovka, ale opět se vrátí do stavu, že čeká na přihlášení. Teprve po druhém zadání se úspěšně dostanu do lobby.
Zajímavé je, že druhé přihlášení proběhne úspěšně i tehdy, když se rozhodnu přihlásit pod jiným uživatelem, než byl ten neúspěšný.

**Comment by Dimitros617** [comment]
Tato chyba je závislá na klientovy a záleží na prohlížeči a verzi.
