### ISSUE TITLE
Banka: administrátorské výpisy napříč státy vidět pouze pro aktuální hru + čas transakce (P1)

### ISSUE THREAD

**Issue by lomikel** [Dimitros617/Climate_rules#43]
Při přepnutí do administrátorského nástroje v bance se zobrazí výpis všech transakcí s centrální bankou, ale zřejmě funguje napříč hrami.
Po založení a spuštění nové hry se mi v přehledu zobrazují data i dřívějších transakcí v testovacích lobby.
Čas transakcí je zvláštní. Platbu jsem zadával po 9. hodině. Je to serverem?

![image](https://user-images.githubusercontent.com/11619693/191440929-544e3a57-25de-48fd-890f-2f44f097b0ff.png)

**Comment by Dimitros617** [comment]
Opraveno až na časy, ty se získávají na straně serveru a ten je pak rozhozený protože nepočítá s letním a zimním časem
